# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='a Great author', max_length=1000)),
                ('image', models.ImageField(upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='a nice book to read', max_length=1000)),
                ('pages', models.IntegerField()),
                ('image', models.ImageField(upload_to='books/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapi.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapi.Book')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='pics/')),
                ('birthdate', models.DateField(null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('favourites', models.ManyToManyField(to='bookapi.Category')),
                ('follows', models.ManyToManyField(to='bookapi.Author')),
                ('likes', models.ManyToManyField(related_name='users_likes', to='bookapi.Book')),
                ('rated', models.ManyToManyField(related_name='users_rated', through='bookapi.Rate', to='bookapi.Book')),
                ('read', models.ManyToManyField(related_name='users_read', to='bookapi.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishes', models.ManyToManyField(related_name='users_wishes', to='bookapi.Book')),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapi.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapi.Category'),
        ),
    ]
