# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0013_auto_20170429_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(default='a Great author', max_length=1000),
        ),
    ]
