# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0015_auto_20170430_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
